### ISSUE TITLE
Tags API sort param need support text(tag_content)

### ISSUE THREAD

**Issue by tempo0829** [readr-media/readr-restful#185]
GET `/tags?max_result=20&page=1&sort=text` is not work.

**Comment by ichiaohsu** [comment]
I think that's because `text` is not a valid field in database. It should be `tag_content` instead. However, use `sort=tag_content` would not work, since in `validateSorting` acceptable field is `-(text|updated_at|created_at|related_reviews|related_news)`. We should either change the validate field or try to synchronize the field in JSON and DATABASE.

**Comment by tempo0829** [comment]
another feature request:

GET `tags/count` need support keyword param.

when we get tags data by specific keyword, we also need update tags count info for pagination

**Comment by FalseChord** [comment]
For new feature request, should reopen it.
