### ISSUE TITLE
cannot unmarshal number into Go struct

### ISSUE THREAD

**Issue by chiangkeith** [readr-media/readr-restful#305]
**Describe the bug**
If I give a req to restful with created_by: (Number), will get Error like `'{"Error":"json: cannot unmarshal number into Go struct field ChoicesEmbeddedPoll.created_by of type models.Stunt"}'`.

I've checked the model of poll. The `created_by` is `models.NullInt`, that means i'm not supposed to be treated with this error.

**To Reproduce**
Send a Post request to readr-restful, and remember to give created_by with a Number like:

```
{
	"start_at":"2018-12-14T10:28:18.835Z",
	"end_at":"2018-12-14T19:28:18.835+08:00",
	"title":"2018 年底很多歌手出新專輯",
	"description":"你最想聽誰的新專輯呢？",
	"frequency":0,
	"max_choice":2,
	"changeable":1,
	"published_at":"2018-12-14T18:28:41.165+08:00",
	"updated_at":"2018-12-14T18:28:41.177+08:00",
	"status":1,
	"created_by": 648,
	"active":1
}
```
Then you will get the response like:
> '{"Error":"json: cannot unmarshal number into Go struct field ChoicesEmbeddedPoll.created_by of type models.Stunt"}'

**Expected behavior**
Should get status 201 instead of error.

**Comment by ichiaohsu** [comment]
In #304 embedded `created_by` had changed from simple integer, e.g.

```json
"created_by": 648
```
 to an object: 
```json
"created_by": {
       "id": 648
}
```

The struct `Poll` in models.go is the basic mapping. In practice, the JSON input unmarshallings are far more complicated than that.

It appears I had incidentally introduced the behavior changes because of the implementation of embedded `created_by`. I don't see a proper solution, unless we implemented a embedded `created_by` struct for output while accepting simple integer `created_by` for JSON input.
